#pragma once
//
// File: leg_pos.cpp
//
// MATLAB Coder version            : 23.2
// C/C++ source code generated on  : 10-Oct-2024 20:55:32
//

// Include Files
#include <cmath>
#include <numbers>
namespace app::observer {
// Function Definitions
//
// LEG_POS
//     POS = LEG_POS(PHI1,PHI2)
//
// Arguments    : double phi1
//                double phi2
//                double pos[2] l0 phi
// Return Type  : void
//
void leg_pos(double phi1, double phi2, double pos[2]) {
    double a_tmp;
    double b_a_tmp;
    //     This function was generated by the Symbolic Math Toolbox version 23.2.
    //     2024-10-10 20:43:15
    a_tmp   = std::sin(phi1) * 0.18 + std::sin(phi2) * 0.18;
    b_a_tmp = std::cos(phi1) * 0.18 + std::cos(phi2) * 0.18;
    pos[0]  = std::sqrt(a_tmp * a_tmp + b_a_tmp * b_a_tmp);
    pos[1]  = 1.5707963267948966 - std::atan2(a_tmp, b_a_tmp);
    if (pos[1] < -std::numbers::pi) {
        pos[1] += 2 * std::numbers::pi;
    } else if (pos[1] > std::numbers::pi) {
        pos[1] -= 2 * std::numbers::pi;
    }
}

} // namespace app::observer