//
// File: leg_conv.cpp
//
// MATLAB Coder version            : 23.2
// C/C++ source code generated on  : 09-Oct-2024 20:38:47
//

// Include Files
#include "leg_conv.h"
#include "rt_nonfinite.h"
#include "rt_defines.h"
#include <cmath>

// Function Declarations
static double rt_atan2d_snf(double u0, double u1);

// Function Definitions
//
// Arguments    : double u0
//                double u1
// Return Type  : double
//
static double rt_atan2d_snf(double u0, double u1)
{
  double y;
  if (std::isnan(u0) || std::isnan(u1)) {
    y = rtNaN;
  } else if (std::isinf(u0) && std::isinf(u1)) {
    int i;
    int i1;
    if (u0 > 0.0) {
      i = 1;
    } else {
      i = -1;
    }
    if (u1 > 0.0) {
      i1 = 1;
    } else {
      i1 = -1;
    }
    y = std::atan2(static_cast<double>(i), static_cast<double>(i1));
  } else if (u1 == 0.0) {
    if (u0 > 0.0) {
      y = RT_PI / 2.0;
    } else if (u0 < 0.0) {
      y = -(RT_PI / 2.0);
    } else {
      y = 0.0;
    }
  } else {
    y = std::atan2(u0, u1);
  }
  return y;
}

//
// LEG_CONV
//     T = LEG_CONV(F,Tp,PHI1,PHI2)
//
// Arguments    : double F
//                double Tp
//                double phi1
//                double phi2
//                double T[2]
// Return Type  : void
//
void leg_conv(double F, double Tp, double phi1, double phi2, double T[2])
{
  double a_tmp;
  double t12;
  double t20;
  double t4;
  double t5;
  //     This function was generated by the Symbolic Math Toolbox version 23.2.
  //     2024-10-09 20:33:01
  t4 = std::sin(phi1);
  t5 = std::sin(phi2);
  t12 = std::cos(phi1) * 0.18 + std::cos(phi2) * 0.18;
  a_tmp = t4 * 0.18 + t5 * 0.18;
  t4 = rt_atan2d_snf(a_tmp, (t4 * 0.0 + t5 * 0.0) + t12);
  t20 = phi1 - t4;
  t5 = phi2 - t4;
  t4 = Tp * (1.0 / std::sqrt(t12 * t12 + a_tmp * a_tmp));
  T[0] = F * std::sin(t20) * -0.18 + t4 * std::cos(t20) * 0.18;
  T[1] = F * std::sin(t5) * -0.18 + t4 * std::cos(t5) * 0.18;
}

//
// File trailer for leg_conv.cpp
//
// [EOF]
//
